---
- name: Remove takt-public image
  community.docker.docker_image:
    name: "{{ takt_public_image }}"
    source: pull
    state: absent

- name: Pull new takt_public
  community.docker.docker_image:
    name: "{{ takt_public_image }}"
    source: pull
    state: present

- name: Create takt network and connect containers
  community.docker.docker_network:
    name: takt-network
    state: present

- name: Start takt-public
  community.docker.docker_container:
    name: "{{ containers_takt_public }}"
    state: started
    image: "{{ takt_public_image }}"
    restart_policy: "unless-stopped"
    networks:
      - name: takt-network

- name: Start nginx
  community.docker.docker_container:
    name: "{{ containers_nginx }}"
    state: started
    image: "nginx:{{ nginx_version }}"
    restart_policy: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/lib/takt_host/takt_nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/var/lib/takt_host/certbot:/var/www/certbot:ro"
      - "/var/lib/takt_host/letsencrypt:/etc/letsencrypt:ro"
    networks:
      - name: takt-network

- name: Start certbot
  community.docker.docker_container:
    name: "certbot"
    state: started
    image: "certbot/certbot:latest"
    command: "certonly --webroot --webroot-path /var/www/certbot/ --email andreygolubkow@gmail.com --agree-tos --no-eff-email -d {{ takt_host_url }}"
    volumes:
      - "/var/lib/takt_host/certbot:/var/www/certbot/:rw"
      - "/var/lib/takt_host/letsencrypt:/etc/letsencrypt/:rw"
    networks:
      - name: takt-network