---
- name: Prepare Self-Signed SSL cert
  ansible.builtin.include_tasks: selfsignedssl.yml

- name: Install nginx
  ansible.builtin.include_tasks: nginx.yml

- name: Install application
  ansible.builtin.include_tasks: application.yml
