---
- name: Installing additional packages 
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      # - lsb-release
      # - python3-pip
    update-cache: true
    cache_valid_time: 86400
  become: true


- name: Create a directory
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Add key Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg
  become: true

- name: Install stable repository
  apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
    state: present
    update-cache: true
    filename: docker
  become: true

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update-cache: true
    cache_valid_time: 86400
  become: true

- name: Check Docker installed and restarted
  service:
    name: docker
    state: restarted
    enabled: true
  become: true

- name: Get latest version Docker-compose
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    body_format: json
  register: page

- name: Install Docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: "0755"

- name: Finishing install
  block:
    - name: Add users in groups Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
